name: Dev deployment from Github to AWS beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Logi n to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: hilare/docker-react:latest

      # Get current timestamp for tracking version of beanstalk
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      # use action to replace ':' with '-' in the timestamp string (optional)
      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs-time }}"
          replace-with: '-'
          flags: 'g'

      # create a zipped package excluding node_modules, to send Dockerrun.aws.json to beanstalk
      - name: Generete Deployment Package
        run: zip -r deploy-v1.zip * -x "**node_modules"

      # use the action to push zip to beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy-v1.zip
          use_existing_version_if_available: true