name: Dev deployment from Github to AWS beanstalk
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: hilare/docker-react:latest

      #  generating sequential build numbers
      - name: Build Number Generator
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}

      # create a zipped package excluding node_modules, to send Dockerrun.aws.json to beanstalk
      - name: Generete Deployment Package
        run: zip -r deploy.zip * -x '*node_modules*' '*.git*'

      # use the action to push zip to beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: docker-react-${{ steps.buildnumber.outputs.build_number }}
          region: us-east-1
          deployment_package: deploy.zip